LibraryManagementSystem/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('accounts.urls')),
                  path('admindash/', include('admin_dash.urls')),
                  path('userdash/', include('user_dash.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path, include
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('change/password', views.password_change, name='password_change'),
    path('', views.login, name='login'),
    path('send/email/verification', views.send_email_verification_code, name='send_email_verification_code'),
    path('email/verify', views.verify_email, name='verify_email'),
    path('logout', views.logout, name='logout')
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)


class MyUserManager(BaseUserManager):
    def create_user(self, email, password=None):
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None):
        user = self.create_user(
            email,
            password=password,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class MyUser(AbstractBaseUser):
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,
    )
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    is_staff_member = models.BooleanField(default=False)
    last_login = models.DateTimeField(blank=True, null=True, verbose_name="last login")
    is_email_verified = models.BooleanField(default=False)
    is_user_verified = models.BooleanField(default=False)

    objects = MyUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin


class EmailVerification(models.Model):
    users = models.OneToOneField(MyUser, on_delete=models.CASCADE)
    verification_code = models.CharField(max_length=6)
    created_date_time = models.DateTimeField(auto_now_add=True)
    total_try_request = models.IntegerField()
    block_time = models.DateTimeField(default='2020-01-01')

    def __str__(self):
        return self.users.email

accounts/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import MyUser
from django.contrib.auth.hashers import make_password


class MyUserCreationForm(forms.ModelForm):
    class Meta:
        model = MyUser
        fields = ['email', 'password']

    def clean_password(self):
        password1 = self.cleaned_data['password']
        special_sym = ['$', '@', '#', '%']

        if not any(char.isdigit() for char in password1):
            raise forms.ValidationError('Password should have at least one numeral')

        if not any(char.isupper() for char in password1):
            raise forms.ValidationError('Password should have at least one uppercase letter')

        if not any(char.islower() for char in password1):
            raise forms.ValidationError('Password should have at least one lowercase letter')

        if not any(char in special_sym for char in password1):
            raise forms.ValidationError('Password should have at least one of the symbols $@#')
        return make_password(self.cleaned_data['password'])


class ChangePasswordForm(forms.ModelForm):
    class Meta:
        model = MyUser
        fields = ["password"]

    def clean_password(self):
        password1 = self.cleaned_data['password']
        special_sym = ['$', '@', '#', '%']

        if not any(char.isdigit() for char in password1):
            raise forms.ValidationError('Password should have at least one numeral')

        if not any(char.isupper() for char in password1):
            raise forms.ValidationError('Password should have at least one uppercase letter')

        if not any(char.islower() for char in password1):
            raise forms.ValidationError('Password should have at least one lowercase letter')

        if not any(char in special_sym for char in password1):
            raise forms.ValidationError('Password should have at least one of the symbols $@#')
        return password1

accounts/views.py
from datetime import datetime, timezone
from random import randint
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import make_password
from django.shortcuts import render, HttpResponse, redirect
from .models import MyUser, EmailVerification
from .forms import MyUserCreationForm, ChangePasswordForm
from django.core.mail import send_mail
from LibraryManagementSystem.settings import EMAIL_HOST_USER


# Create your views here.

# user register
def register(request):
    if request.user.is_authenticated:
        if request.user.is_admin:
            return redirect('admin_dash:home')
        else:
            return redirect('user_dash:book_list')
    context = {'form': MyUserCreationForm()}
    if request.method == 'POST':
        email = request.POST.get('email')
        context['email'] = email
        if request.user.is_authenticated:
            return redirect('/')
        form = MyUserCreationForm(request.POST)

        password1 = request.POST.get('password')
        password2 = request.POST.get('password2')
        if password1 != password2:
            context['errors'] = 'Password and conform Password didnot match'
            context['email'] = request.POST['email']
            return render(request, 'accounts/register.html', context)
        if form.is_valid():
            form.save()
            email = email
            password = password1
            user = auth.authenticate(email=email, password=password)
            if user is not None:
                auth.login(request, user)
                return redirect('accounts:send_email_verification_code')
            else:
                context['errors'] = "something went wrong"
                return render(request, 'accounts/login.html', context)
        else:
            context['errors'] = form.errors
            context['email'] = request.POST['email']

    return render(request, 'accounts/register.html', context)


# sending email verification code
@login_required()
def send_email_verification_code(request):
    user = request.user
    if MyUser.objects.get(email=request.user).is_email_verified:
        return HttpResponse('email already Verified')
    code = randint(100000, 999999)  # verification code
    create_date = datetime.now()
    total_try_requests = 0

    if not EmailVerification.objects.filter(users=user).exists():
        EmailVerification.objects.create(
            users=user,
            verification_code=code,
            created_date_time=create_date,
            total_try_request=total_try_requests,
        )
    else:
        email_verification = EmailVerification.objects.get(users=user)
        block_date = email_verification.block_time
        now = datetime.now(timezone.utc)
        difference = now - block_date
        if difference.total_seconds() < 300:
            return HttpResponse(f'You have been block for {difference} second')
        EmailVerification.objects.filter(users=user).update(
            verification_code=code,
            created_date_time=create_date,
            total_try_request=total_try_requests,
        )
    send_mail(
        "Email Verification Code",
        f"Your email verification code is {code}",
        EMAIL_HOST_USER,
        [EmailVerification.objects.get(users=user).users.email],
    )
    return redirect('accounts:verify_email')


@login_required()
def verify_email(request):
    if MyUser.objects.get(email=request.user).is_email_verified:
        return redirect('user_dash:profile_create')
    if request.method == 'POST':
        if MyUser.objects.get(email=request.user).is_email_verified:
            return redirect('user_dash:profile_create')

        request_code = request.POST['otp1'] + request.POST['otp2'] + request.POST['otp3'] + request.POST['otp4'] + \
                       request.POST['otp5'] + request.POST['otp6']  # code send from user to verify
        code = EmailVerification.objects.get(users=request.user).verification_code
        if request_code == code:
            MyUser.objects.filter(email=request.user).update(is_email_verified=True)
            return redirect('user_dash:profile_create')
        else:
            context = {'error': 'code you have entered is wrong'}
            return render(request, 'accounts/verify_email.html', context)
    return render(request, 'accounts/verify_email.html')


# user login
def login(request):
    if request.user.is_authenticated:
        if request.user.is_admin:
            return redirect('admin_dash:home')
        else:
            return redirect('user_dash:book_list')
    if request.method == 'POST':
        if request.user.is_authenticated:
            if request.user.is_admin:
                return redirect('admin_dash:home')
            else:
                return redirect('user_dash:book_list')
        email = request.POST['email']
        password = request.POST['password']
        user = auth.authenticate(email=email, password=password)
        if user is not None:
            auth.login(request, user)
        else:
            context = {"errors": "User name or password is incorrect"}
            return render(request, 'accounts/logi'
                                   'n.html', context)

        if request.user.is_admin:
            return redirect('admin_dash:home')
        else:
            return redirect('user_dash:book_list')
    return render(request, 'accounts/login.html')

#password change
@login_required()
def password_change(request):
    context = {}
    if request.method == 'POST':
        old_password = request.POST['old_password']
        password = request.POST['password']
        password2 = request.POST['password2']
        data = {"password": password, 'password2': password2, "old_password": old_password}

        if not request.user.check_password(old_password):
            context['errors'] = 'Your password didnot match with old password'
        if old_password == password:
            context['errors'] = 'old password cannot be new password'
        if password != password2:
            context['errors'] = 'your conformed password didnot matched'
        form = ChangePasswordForm(data)
        if form.is_valid():
            MyUser.objects.filter(email=request.user).update(password=make_password(form.data['password']))
        else:
            context['errors'] = form.errors
    return render(request, 'accounts/change_password.html', context)

#logout
def logout(request):
    auth.logout(request)
    return redirect('/')

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}
{% block body %}
    <div class="container-fluid" id="container-wrapper">
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Change Password</h1><br>
        </div>

        <div class="row mb-3">
            {% if errors %}
            <div class="container alert alert-danger">

                {{ errors }}
            </div>
            {% endif %}
            <!-- Earnings (Monthly) Card Example -->
            <form method="post" class="ml-4">

                {% csrf_token %}
                Old Password:<input type="text" class="form-control" name="old_password" required><br><br>
                new Password:<input type="text" class="form-control" name="password" required><br><br>
                Re-enter new Password:<input type="text" class="form-control" name="password2" required><br><br>
                <input type="submit" class="btn btn-success">
            </form>
            <!-- Earnings (Annual) Card Example -->

        </div>
        <!---Container Fluid-->

    </div>
    <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
{% endblock %}

accounts/templates/accounts/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- ===== CSS Stylesheet ===== -->

    <!-- <link rel="stylesheet" href="assets/css/bootstrap.min.css"> -->
    <link rel="stylesheet" href="{% static 'accounts/assets/css/styles.css' %}">

    <!-- ===== BOX ICONS ===== -->
    <link href='https://cdn.jsdelivr.net/npm/boxicons@2.0.5/css/boxicons.min.css' rel='stylesheet'>

    <title>LMS - LOGIN | REGISTER</title>
</head>

<body>
<div class="login">
    <div class="login-content">

        <div class="login-img">
            <img src="{% static 'accounts/assets/img/img-login.svg' %}" alt="">
        </div>

        <div class="login-forms">

            <form method="post" class="login-register" id="login-in">
                {% csrf_token %}
                <h1 class="login-title"><b>SIGN <span>IN</span></b></h1>
                {% if errors %}
                    <h3 class="error" style="color: red;"><b>{{ errors }}</b></h3>
                {% endif %}

                <div class="login-box">
                    <i class='bx bx-envelope login-icon'></i>
                    <input type="email" name="email" placeholder="Enter email" class="login-input" required>
                </div>

                <div class="login-box">
                    <i class='bx bx-lock-alt login-icon'></i>
                    <input type="password" name="password" placeholder="Enter Password" class="login-input" required>
                </div>

                <input value="Sign In" type="submit" href="" class="login-button"
                       style="border: none;display: inline-block">

                <div>
                    <span class="login-account">Don't have an Account ?</span>
                    <a href="{% url 'accounts:register' %}" class="login-signin" id="sign-up">Sign Up Now</a>
                </div>
            </form>


        </div>
    </div>
</div>

<!--===== Custom JavaScript =====-->
{#<script src="{% static 'accounts/assets/js/main.js' %}"></script>#}

</body>

</html>

accounts/templates/accounts/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- ===== CSS Stylesheet ===== -->

    <!-- <link rel="stylesheet" href="assets/css/bootstrap.min.css"> -->
    <link rel="stylesheet" href="{% static 'accounts/assets/css/styles.css' %}">

    <!-- ===== BOX ICONS ===== -->
    <link href='https://cdn.jsdelivr.net/npm/boxicons@2.0.5/css/boxicons.min.css' rel='stylesheet'>

    <title>LMS - LOGIN | REGISTER</title>
</head>

<body>
<div class="login">
    <div class="login-content">

        <div class="login-img">
            <img src="{% static 'accounts/assets/img/img-login.svg' %}" alt="">
        </div>

        <div class="login-forms">

            <form method="post" class="login-register" id="login-in">
                {% csrf_token %}
                <h1 class="login-title"><b>SIGN <span>UP</span></b></h1>
                {% if errors %}
                    <h3 class="error" style="color: red;"><b>{{ errors }}</b></h3>
                {% endif %}

                <div class="login-box">
                    <i class='bx bx-envelope login-icon'></i>
                    <input type="text" name="email" value="{{ email }}" placeholder="Email" maxlength="255" class="login-input" required>
                </div>

                <div class="login-box">
                    <i class='bx bx-lock-alt login-icon'></i>
                    <input type="password" class="login-input" placeholder="Enter Your Password" name="password"
                           maxlength="128" required>
                </div>

                <div class="login-box">
                    <i class='bx bx-lock-alt login-icon'></i>

                    <input type="password" name="password2" placeholder="Confirm Password" class="login-input"
                           maxlength="128" minlength="8" required id="id_password2">
                </div>

                <input value="Sign Up" type="submit" href="" class="login-button"
                       style="border: none;display: inline-block">

                <div>
                    <span class="login-account">Already have an Account ?</span>
                    <a href="{% url 'accounts:login' %}" class="login-signup" id="sign-in">Sign In Now</a>
                </div>

{#                <div class="login-social">#}
{#                    <a href="#" class="login-social-icon" title="Login With Gmail"><i class='bx bxl-google'></i></a>#}
{#                </div>#}
            </form>


        </div>
    </div>
</div>

<!--===== Custom JavaScript =====-->
<script src="{% static 'accounts/assets/js/main.js' %}"></script>

</body>

</html>

accounts/templates/accounts/verify_email.html
{#<form method="post">#}
{#    {% csrf_token %}#}
{#    {% if error %}{{ error }}{% endif %}<br>#}
{#    verification code<input type="text" name="code">#}
{##}
{#    <input type="submit">#}
{#    <a href="{% url 'accounts:send_email_verification_code' %}">Resend Verification code</a>#}
{#</form>#}
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <title>Verify Email</title>
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/assets/css/styles.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
</head>

<body style="background-color: var(--primary-color);">

<div class="container height-100 d-flex justify-content-center align-items-center">
    <div class="position-relative">
        <div class="card p-2 text-center">
            <div><span>A six digit code has been sent to your email<br></span> <b>{{ request.user }}</b>
            </div>
            {% if error %}
                <div>
                    <span>{{ error }}<br></span>
                </div>
            {% endif %}
            <h6 class="mt-2">Please enter the code to verify your account</h6>
            <form method="post">
                <div id="otp" class="inputs d-flex flex-row justify-content-center mt-2">
                    {% csrf_token %}
                    <input class="m-2 text-center form-control rounded" name="otp1" type="text" id='ist' maxlength="1"
                           onkeyup="clickEvent(this,'sec')">
                    <input class="m-2 text-center form-control rounded" name="otp2" type="text" id='sec' maxlength="1"
                           onkeyup="clickEvent(this,'third')">
                    <input class="m-2 text-center form-control rounded" name="otp3" type="text" id='third' maxlength="1"
                           onkeyup="clickEvent(this,'fourth')">
                    <input class="m-2 text-center form-control rounded" name="otp4" type="text" id='fourth'
                           maxlength="1"
                           onkeyup="clickEvent(this,'fifth')">
                    <input class="m-2 text-center form-control rounded" name="otp5" type="text" id='fifth' maxlength="1"
                           onkeyup="clickEvent(this,'sixth')">
                    <input class="m-2 text-center form-control rounded" name="otp6" type="text" id='sixth'
                           maxlength="1">

                </div>
                <div class="mt-4">
                    <input type="submit" value="Verify" class="btn btn-info px-4 validate">
                </div>
            </form>
        </div>
        <div class="card-2">
            <div class="content d-flex justify-content-center align-items-center"> <span>Didn't get the otp
						code?</span>
                <a href="{% url 'accounts:send_email_verification_code' %}"> Resend Verification code</a>
            </div>
        </div>
    </div>
</div>

<script>
    function clickEvent(first, last) {
        if (first.value.length) {
            document.getElementById(last).focus();
        }
    }
</script>

</body>

</html>