LibraryManagementSystem/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('accounts.urls')),
                  path('admindash/', include('admin_dash.urls')),
                  path('userdash/', include('user_dash.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path, include
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('change/password', views.password_change, name='password_change'),
    path('', views.login, name='login'),
    path('send/email/verification', views.send_email_verification_code, name='send_email_verification_code'),
    path('email/verify', views.verify_email, name='verify_email'),
    path('logout', views.logout, name='logout')
]

admin_dash/urls.py
from django.urls import path
from . import views

app_name = 'admin_dash'

urlpatterns = [
    path('', views.home, name='home'),
    # users
    path('add/users/', views.UsersCreateView.as_view(), name='add_users'),
    path('view/users/', views.UserListView.as_view(), name='user_list_view'),
    # profile
    path('update/user/<str:pk>', views.UserUpdateView.as_view(), name='update_user'),
    path('block/user/<str:email>', views.block_user, name='block_user'),
    path('verify/user/email/<str:email>', views.verify_email, name='verify_email'),
    path('verify/user/<str:email>', views.verify_user, name='verify_user'),
    path('profile/view/<str:pk>', views.ProfileListView.as_view(), name='profile_list_view'),
    path('profile/create/<str:pk>', views.CreateProfile.as_view(), name='create_profile'),
    path('profile/update/<str:pk>', views.ProfileUpdateView.as_view(), name='profile_update'),
    # books
    path('book/create/', views.BookCreateView.as_view(), name='book_create'),
    path('book/update/<str:pk>', views.BookUpdate.as_view(), name='book_update'),
    path('book/list/', views.BookListView.as_view(), name='book_list'),
    path('book/copies/create/<str:pk>', views.BookCopiesCreateView.as_view(), name='book_copies_create'),
    path('book/copies/view/<str:pk>', views.BookCopiesListView.as_view(), name='book_copies_list'),
    # lend book
    path('book/lend/student/', views.user_id, name='student'),
    path('book/student/book/', views.book, name='book'),
    path('book/lend/student/book/', views.user_book, name='user_book'),
    path('book/lend/student/book/conform', views.lend_book, name='lend_book'),
    path('book/return/', views.return_book, name='return_book'),
    path('book/return/conform/', views.return_conform, name='return_book_conform'),
    # request book
    path('book/request/view', views.RequestBookListView.as_view(), name='request_book_view'),
    path('book/request/cancel/<str:pk>', views.cancel_book_request, name='cancel_book_request'),
    #book history
    path('book/history/',views.MyBookLendHistory.as_view(),name='book_history')
]

admin_dash/models.py
from django.db import models

# Create your models here.

books/models.py
from django.db import models

# Create your models here.
from accounts.models import MyUser


class Author(models.Model):
    full_name = models.CharField(max_length=200)

    def __str__(self):
        return self.full_name


class BookCategory(models.Model):
    name = models.CharField(max_length=100)
    desc = models.TextField(max_length=300)

    def __str__(self):
        return self.name


class Book(models.Model):
    author = models.CharField(max_length=100)
    title = models.CharField(max_length=500)
    category = models.ForeignKey(BookCategory, on_delete=models.PROTECT)
    publication_name = models.CharField(max_length=300, blank=True, null=True)
    publication_date = models.DateField()

    def __str__(self):
        return self.title


class BookCopies(models.Model):
    book = models.ForeignKey(Book, on_delete=models.PROTECT)
    isbn = models.CharField(max_length=17, unique=True)
    rfid = models.CharField(max_length=20, unique=True, blank=True, null=True)
    is_book_lost = models.BooleanField(default=False)
    is_book_available = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.book.title} {self.isbn}'


class LendBook(models.Model):
    user = models.ForeignKey(MyUser, on_delete=models.PROTECT)
    book = models.ForeignKey(BookCopies, on_delete=models.PROTECT)
    date_of_issue = models.DateField(auto_now_add=True)
    date_of_return = models.DateField(null=True, blank=True)
    fine = models.IntegerField(default=0)
    is_return = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.user} {self.book.book.title}'

profiles/models.py
from accounts.models import MyUser
from django.db import models


# Create your models here.

class Profiles(models.Model):
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
        ('N', 'Rather Not Say'),
    )

    user = models.OneToOneField(MyUser, on_delete=models.PROTECT)
    profile_image = models.ImageField(blank=True, null=True)
    full_name = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=10, unique=True)
    dob = models.DateField(verbose_name='Date Of Birth')
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    rf_id = models.CharField(max_length=100, unique=True, blank=True, null=True)

    def __str__(self):
        return self.full_name

admin_dash/views.py
from django.contrib import messages
from django.shortcuts import render, HttpResponse, redirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, ListView, UpdateView
from accounts.models import MyUser
from profiles.models import Profiles
from .forms import UsersForms, ProfileCreateForm, BookForm, BookCopiesForm, ProfileUpdate
from books.models import Book, BookCopies, LendBook
from datetime import date
from user_dash.models import RequestBook
from decorator import is_admin
from django.core.mail import send_mail
from LibraryManagementSystem.settings import EMAIL_HOST_USER


# from

# Create your views here.


# dashboard home
@is_admin()
def home(request):
    context = {
        'users': MyUser.objects.all().count(),
        'total_book': Book.objects.all().count(),
        'book_request': RequestBook.objects.all().count(),
        'book_lend': LendBook.objects.all().count(),
        'book_copies': BookCopies.objects.all().count(),
        'book_return': LendBook.objects.all().filter(is_return=True).count(),
    }

    return render(request, 'admin_dash/admin.html', context)


# create User
@method_decorator(is_admin(), name='dispatch')
class UsersCreateView(CreateView):
    form_class = UsersForms
    template_name = 'admin_dash/user_create_update.html'
    success_message = 'User Created Successfully'

    def get_success_url(self, **kwargs):
        users = MyUser.objects.last()
        return reverse_lazy('admin_dash:create_profile', kwargs={'pk': users.pk})


# update user
@method_decorator(is_admin(), name='dispatch')
class UserUpdateView(UpdateView):
    form_class = UsersForms
    model = MyUser
    template_name = 'admin_dash/user_create_update.html'
    success_message = 'User Created Successfully'

    def get_success_url(self, **kwargs):
        users = MyUser.objects.last()
        return reverse_lazy('admin_dash:user_list_view')


# list all users
@method_decorator(is_admin(), name='dispatch')
class UserListView(ListView):
    model = MyUser
    template_name = 'admin_dash/user_list_view.html'
    context_object_name = 'users'


# admin verifying email
@is_admin()
def verify_email(request, email):
    MyUser.objects.filter(email=email).update(is_email_verified=True)
    return redirect('admin_dash:user_list_view')


# admin Verify User
@is_admin()
def verify_user(request, email):
    MyUser.objects.filter(email=email).update(is_user_verified=True)
    return redirect('admin_dash:user_list_view')


# admin block user
@is_admin()
def block_user(request, email):
    MyUser.objects.filter(email=email).update(is_active=False)
    return redirect('admin_dash:user_list_view')


# viewing user profile
@method_decorator(is_admin(), name='dispatch')
class ProfileListView(ListView):
    model = Profiles
    template_name = 'admin_dash/profile_view.html'
    context_object_name = 'profiles'

    def get_queryset(self):
        queryset = Profiles.objects.filter(user__pk=self.kwargs['pk'])
        return queryset

    def get(self, *args, **kwargs):
        if not Profiles.objects.filter(user__pk=self.kwargs['pk']).exists():
            return redirect(f'/admindash/profile/create/{self.kwargs["pk"]}')
        return super(ProfileListView, self).get(*args, **kwargs)


# creating user profile
@method_decorator(is_admin(), name='dispatch')
class CreateProfile(CreateView):
    form_class = ProfileCreateForm
    template_name = 'admin_dash/create_update_profile.html'
    success_url = '/profile/view/'

    def get_success_url(self):
        return reverse_lazy('admin_dash:user_list_view')

    def get(self, *args, **kwargs):
        print(MyUser.objects.filter(pk=self.kwargs['pk']))
        if Profiles.objects.filter(id=self.kwargs['pk']).exists():
            return redirect('profile:view_profile')
        return super(CreateProfile, self).get(*args, **kwargs)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.kwargs['pk']
        return kwargs


# updating user profile
@method_decorator(is_admin(), name='dispatch')
class ProfileUpdateView(UpdateView):
    form_class = ProfileUpdate
    template_name = 'admin_dash/update_profile.html'
    queryset = Profiles.objects.all()
    success_url = "/profile/view"

    def get_success_url(self, **kwargs):
        return reverse_lazy('admin_dash:user_list_view')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = Profiles.objects.get(id=self.kwargs['pk'])
        return kwargs


# create book
@method_decorator(is_admin(), name='dispatch')
class BookCreateView(CreateView):
    form_class = BookForm
    template_name = 'admin_dash/book_create_update.html'

    def get_success_url(self):
        return reverse_lazy('admin_dash:book_list')


# update book
@method_decorator(is_admin(), name='dispatch')
class BookUpdate(UpdateView):
    form_class = BookForm
    model = Book
    template_name = 'admin_dash/book_create_update.html'

    def get_success_url(self):
        return reverse_lazy('admin_dash:book_list')


# book list view
@method_decorator(is_admin(), name='dispatch')
class BookListView(ListView):
    model = Book
    template_name = 'admin_dash/books_list_view.html'
    context_object_name = 'books'


# adding books
@method_decorator(is_admin(), name='dispatch')
class BookCopiesCreateView(CreateView):
    model = BookCopies
    form_class = BookCopiesForm
    template_name = 'admin_dash/book_copies_create.html'

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['book_id'] = self.kwargs['pk']
        return kwargs

    def get_success_url(self):
        return reverse_lazy('admin_dash:book_list')


# viewing all the books present in database
@method_decorator(is_admin(), name='dispatch')
class BookCopiesListView(ListView):
    model = BookCopies
    template_name = 'admin_dash/books_copies_list_view.html'
    context_object_name = 'copies'

    def get_queryset(self):
        return BookCopies.objects.filter(book__pk=self.kwargs['pk'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['book_id'] = self.kwargs['pk']
        return context


# taking user rfid as input to identify the user
@is_admin()
def user_id(request):
    return render(request, 'admin_dash/student_indentify.html')


# verifying users with rfid
@is_admin()
def book(request):
    if request.method == 'POST':
        context = {}
        rfid = request.POST.get('rfid')
        try:
            profile = Profiles.objects.get(rf_id=rfid)
        except:
            profile = False
        if not profile:
            context['rfid'] = rfid
            context['errors'] = "user doesnot exist"
            return render(request, 'admin_dash/student_indentify.html', context)
        context['profile'] = profile
        return render(request, 'admin_dash/student_lend_book.html', context)


# checking if book exist or not with rfid or isbn
@is_admin()
def user_book(request):
    if request.method == 'POST':
        context = {}
        profile = Profiles.objects.get(rf_id=request.POST.get('rfid'))
        book_id = request.POST.get('book_id')
        book_isbn = BookCopies.objects.filter(isbn=book_id)
        book_rfid = BookCopies.objects.filter(rfid=book_id)
        context['profile'] = profile

        if book_isbn:
            book = BookCopies.objects.get(isbn=book_id)
        elif book_rfid:
            book = BookCopies.objects.get(rfid=book_id)
        else:
            context['errors'] = 'Book does not exist'

            return render(request, 'admin_dash/student_lend_book.html', context)
        context['book'] = book
        context['book_id'] = book.pk
        context['user_email'] = profile.user.email
        return render(request, 'admin_dash/student_book.html', context)


# lending book
@is_admin()
def lend_book(request):
    if request.method == 'POST':
        try:
            # checking if book existence
            books = BookCopies.objects.get(isbn=request.POST.get('isbn'))
            # checking if book is avialable
            if books.is_book_available:
                lend_book_count = LendBook.objects.filter(
                    user=MyUser.objects.get(email=request.POST.get('user'))).filter(is_return=False).count()
                # checking if user have taken book less then 6
                if lend_book_count < 6:
                    available_book_count = BookCopies.objects.filter(book=books.book).filter(
                        is_book_available=True).count()
                    req_book = RequestBook.objects.filter(books=books.book).filter(req_date=date.today()).filter(
                        is_req_cancelled=False)
                    # checking if book is not reserved
                    if not available_book_count > req_book.count():
                        is_eligible = req_book.filter(user=MyUser.objects.get(email=request.POST.get('user')))
                        # incase of book reserve check if the request user have reserved book
                        if is_eligible:
                            pass
                        else:
                            messages.error(request,
                                           'Book has been booked for today please cancel booking to lent this book')
                            return redirect('admin_dash:student')
                    # lending book
                    LendBook.objects.create(
                        user=MyUser.objects.get(email=request.POST.get('user')),
                        book=BookCopies.objects.get(isbn=request.POST.get('isbn'))
                    )
                    # making book as unavailable
                    BookCopies.objects.filter(isbn=request.POST.get('isbn')).update(is_book_available=False)
                    # sending mail
                    send_mail(

profiles/views.py
from django.shortcuts import render

# Create your views here.

admin_dash/templates/admin_dash/book_copies_create.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Add Book Copies{% endblock %}
{% block style %}

{% endblock %}
{% block body %}

        <div class="d-sm-flex  mb-4">
            <h1 class="h3 mb-0 text-gray-800">Add Book Copies</h1>
        </div>

        <div class="row mb-3 ">
            <!-- Earnings (Monthly) Card Example -->
            <div class="col-xl-5 col-md-6 mb-4">
                {% if form.errors %}<div class="alert alert-danger">{{ form.errors }}</div>{% endif %}
                <form method="post">
                    {% csrf_token %}
{#                    {{ form.as_p }}#}
                    Book Name:
                    {{ form.book }}<br>
                    Book Isbn:
                    {{ form.isbn }}<br>
                    Book RFID: (not required)
                    <input type="text" name="rfid" class="form-control" maxlength="20" id="id_rfid"><br>

                    <input type="submit" value="Create Book" class="btn btn-info">
                </form>
            </div>


        </div>
{% endblock %}

admin_dash/templates/admin_dash/book_request.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Book{% endblock %}
{% block body %}
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">My Request History</h1>

    </div>
    {% if messages %}
                    {% for message in messages %}
                        <div{% if message.tags == 'error' %} class="alert alert-danger" {% else %} class="alert alert-success" {% endif %}>{{ message }}</div>
                    {% endfor %}
            {% endif %}

    <div class="row">
        <!-- DataTable with Hover -->
        <div class="col-lg-12">
            <div class="card mb-4">
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                </div>
                <div class="table-responsive p-3">
                    <table class="table table-bordered table-striped table-vcenter js-dataTable-full">
                        <thead class="thead-light">
                        <tr>
                            <th>SN</th>
                            <th>User</th>
                            <th>Title</th>
                            <th>Requested Date</th>
                            <th>Is Request Cancelled</th>

                        </tr>
                        </thead>

                        <tbody>
                        {% for book in books %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ book.user }}</td>
                                <td>{{ book.books.title }}</td>
                                <td>{{ book.req_date }}</td>
                                <td>{% if book.is_req_cancelled %} Booking Cancel {% else %} <a href="{% url 'admin_dash:cancel_book_request' book.pk %}" class="btn btn-danger">Cancel Request</a>{% endif %}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

admin_dash/templates/admin_dash/books_copies_list_view.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Book{% endblock %}
{% block body %}
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Books<a class="btn btn-primary" style="float: right"
                                             href="{% url 'admin_dash:book_copies_create' book_id %}">Add Book</a></h1>
    </div>
    <div class="row">

        <!-- DataTable with Hover -->
        <div class="col-lg-12">
            <div class="card mb-4">
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                </div>
                <div class="table-responsive p-3">
                    <table class="table table-bordered table-striped table-vcenter js-dataTable-full">
                        <thead class="thead-light">
                        <tr>
                            <th>SN</th>
                            <th>Book</th>
                            <th>RFID</th>
                            <th>ISBN</th>
                            <th >Book Status</th>

                        </tr>
                        </thead>

                        <tbody>
                        {% for copy in copies %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ copy.book }}</td>
                                <td>{{ copy.rfid }}</td>
                                <td>{{ copy.isbn }}</td>
                                <td>{% if copy.is_book_available %}Taken{% else %}Available{% endif %}</td>

                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

admin_dash/templates/admin_dash/books_list_view.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Book{% endblock %}
{% block body %}
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Books <a class="btn btn-primary"
                                             href="{% url 'admin_dash:book_create' %}" style="float: right">Add Book</a></h1>
    </div>
    <div class="row">

        <!-- DataTable with Hover -->
        <div class="col-lg-12">
            <div class="card mb-4">
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                </div>
                <div class="table-responsive p-3">
                    <table class="table table-bordered table-striped table-vcenter js-dataTable-full">
                        <thead class="thead-light">
                        <tr>
                            <th>SN</th>
                            <th>Author</th>
                            <th>Title</th>
                            <th>Categories</th>
                            <th>Publication</th>
                            <th>Published Date</th>
                            <th>Action</th>
                            <th>Action</th>
                        </tr>
                        </thead>

                        <tbody>
                        {% for book in books %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ book.author }}</td>
                                <td>{{ book.title }}</td>
                                <td>{{ book.category.name }}</td>
                                <td>{{ book.publication_name }}</td>
                                <td>{{ book.publication_date }}</td>
                                <td><a href="{% url 'admin_dash:book_update' book.pk %}">Update</a></td>
                                <td><a href="{% url 'admin_dash:book_copies_list' book.pk %}">View Copies</a></td>
{#                                <td><a href="{% url 'admin_dash:book_copies_create' book.pk %}">Add Copies</a></td>#}


                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

admin_dash/templates/admin_dash/conform_book_return.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Return Book Conform{% endblock %}
{% block style %}

{% endblock %}
{% block body %}

    <div class="d-sm-flex  mb-4">
        <h1 class="h3 mb-0 text-gray-800">Return Book Confirm</h1>
    </div>

    <div class="row mb-3 ">
        <!-- Earnings (Monthly) Card Example -->
        <div class="col-xl-5 col-md-6 mb-4">
            {% if errors %}
                <ul class="errorlist">
                    {{ errors }}
                </ul>
            {% endif %}
        <form method="post" action="{% url 'admin_dash:return_book_conform' %}">
        {% csrf_token %}
            {% for b in book %}
                User Email: {{ b.user.email }}<br>
                Book Name:{{ b.book.book.title }}<br>
                Author: {{ b.book.book.author }}<br>
                Taken Date: {{ b.date_of_issue }}<br>
                Fine: {{ fine }}
                <input type="hidden" name="book_id" value="{{ b.book.isbn }}"><br><br><br>
                <input type="submit" class="btn btn-secondary">

            {% endfor %}
        </form>
        </div>
    </div>
{% endblock %}

admin_dash/templates/admin_dash/profile_list_view.html
{% extends 'base.html' %}
{% load static %}
{% block title %}USERS{% endblock %}
{% block body %}
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Users</h1>
                <h1 class="h3 mb-0 text-gray-800"><a class="btn btn-outline-primary"
                                                     href="{% url 'admin_dash:add_users' %}">Add Users</a></h1>
    </div>
    <div class="row">

        <!-- DataTable with Hover -->
        <div class="col-lg-12">
            <div class="card mb-4">
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                </div>
                <div class="table-responsive p-3">
                    <table class="table align-items-center table-flush table-hover" id="dataTableHover">
                        <thead class="thead-light">
                        <tr>
                            <th>Profile Pic</th>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Address</th>
                            <th>DOB</th>
                            <th>Gender</th>
                            <th>RFID</th>
                            <th>Action</th>
                        </tr>
                        </thead>

                        <tbody>
                        {% for profile in profiles %}
                            <tr>
                                <td><img src="{{ profile.profile_image.url }}" height="100" width="100"></td>
                                <td>{{ profile.full_name }}</td>
                                <td>{{ profile.user.email }}</td>

                                <td>{{ profile.address }}</td>

                                <td>{{ profile.dob }}</td>

                                <td>{{ profile.gender }}</td>

                                <td>{{ profile.rf_id }}</td>
                                <td><a href="{% url 'admin_dash:profile_update' profile.pk %}">Update</a></td>

                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

admin_dash/templates/admin_dash/profile_view.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Add Users{% endblock %}
{% block body %}
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">View profile</h1>
    </div>
    <div class="row">

        <!-- DataTable with Hover -->
        <div class="col-lg-12">
            <div class="card mb-4">
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                </div>
                <div class="table-responsive p-3">
                    {% for profile in profiles %}
                        Image:<br>
                        {% if profile.profile_image %}
                            <img src="{{ profile.profile_image.url }}" height="350" width="200"><br>
                        {% else %}
                            No Profile Image<br>
                        {% endif %}
                        Name: {{ profile.full_name }}<br>
                        Email: {{ profile.user.email }}<br>
                        Address : {{ profile.address }}<br>
                        Phone Number : {{ profile.phone_number }}<br>
                        Date of birth : {{ profile.dob }}<br>
                        Date of birth : {{ profile.gender }}<br>
                        RFID : {{ profile.rf_id }}<br>
                        <a href="{% url 'admin_dash:profile_update' profile.id %}">Update Profile</a>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

admin_dash/templates/admin_dash/user_list_view.html
{% extends 'base.html' %}
{% load static %}
{% block title %}USERS{% endblock %}
{% block body %}
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Users <a class="btn btn-primary" style="float: right"
                                                   href="{% url 'admin_dash:add_users' %}">Add Users</a></h1>
    </div>
    <div class="row">

        <!-- DataTable with Hover -->
        <div class="col-lg-12">
            <div class="card mb-4">
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                </div>
                <div class="table-responsive p-3">
                    <table class="table table-bordered table-striped table-vcenter js-dataTable-full">

                        <thead class="thead-light">
                        <tr>
                            <th>SN</th>
                            <th>Email</th>
                            <th>User Type</th>
                            <th>Email Verified</th>
                            <th>User Verified</th>
                            <th>Action</th>
                            <th>Action</th>
                            <th>Action</th>
                        </tr>
                        </thead>

                        <tbody>
                        {% for user in users %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ user.email }}</td>
                                {% if user.is_staff_member %}
                                    <td>Staff</td>
                                {% else %}
                                    <td>Student</td>
                                {% endif %}
                                <td>
                                    {% if user.is_email_verified %}
                                        Verified
                                    {% else %}
                                        <a href="{% url 'admin_dash:verify_email' user.email %}">Verify Email</a>
                                    {% endif %}
                                </td>



                                <td>
                                    {% if user.is_user_verified %}
                                        Verified
                                    {% else %}
                                        <a href="{% url 'admin_dash:verify_user' user.email %}">Verify Users</a>
                                    {% endif %}
                                </td>
                            <td>
                                    {% if not user.is_active %}
                                        Blocked
                                    {% else %}
                                        <a href="{% url 'admin_dash:block_user' user.email %}">Block User</a>
                                    {% endif %}
                                </td>
                                <td><a href="{% url 'admin_dash:update_user' user.pk %}">Update</a></td>
                                <td><a href="{% url 'admin_dash:profile_list_view' user.pk %}">View Profile</a></td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}