LibraryManagementSystem/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('accounts.urls')),
                  path('admindash/', include('admin_dash.urls')),
                  path('userdash/', include('user_dash.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path, include
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('change/password', views.password_change, name='password_change'),
    path('', views.login, name='login'),
    path('send/email/verification', views.send_email_verification_code, name='send_email_verification_code'),
    path('email/verify', views.verify_email, name='verify_email'),
    path('logout', views.logout, name='logout')
]

user_dash/urls.py
from django.urls import path
from . import views

app_name = 'user_dash'

urlpatterns = [
    path('book/list/', views.BookListView.as_view(), name='book_list'),
    path('book/history/', views.MyBookLendHistory.as_view(), name='book_list_history'),
    path('book/request/view', views.ViewRequestBook.as_view(), name='request_book_list_view'),
    path('book/request/<str:pk>', views.request_book, name='request_book'),
    path('profile/create/', views.CreateProfile.as_view(), name='profile_create'),
    path('profile/view/', views.ProfileListView.as_view(), name='profile_list_view'),
    path('profile/update/', views.ProfileUpdateView.as_view(), name='profile_update'),
]

profiles/models.py
from accounts.models import MyUser
from django.db import models


# Create your models here.

class Profiles(models.Model):
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
        ('N', 'Rather Not Say'),
    )

    user = models.OneToOneField(MyUser, on_delete=models.PROTECT)
    profile_image = models.ImageField(blank=True, null=True)
    full_name = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=10, unique=True)
    dob = models.DateField(verbose_name='Date Of Birth')
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    rf_id = models.CharField(max_length=100, unique=True, blank=True, null=True)

    def __str__(self):
        return self.full_name

user_dash/models.py
from django.db import models
from books.models import Book
from accounts.models import MyUser


# Create your models here.

class RequestBook(models.Model):
    books = models.ForeignKey(Book, on_delete=models.PROTECT)
    user = models.ForeignKey(MyUser, on_delete=models.PROTECT)
    req_date = models.DateField(auto_now_add=True)
    is_req_cancelled = models.BooleanField(default=False)

    class Meta:
        unique_together = ['books', 'user', 'req_date']

user_dash/forms.py
from django import forms

from accounts.models import MyUser
from profiles.models import Profiles


class ProfileForms(forms.ModelForm):
    class Meta:
        model = Profiles
        fields = ['user', 'profile_image', 'full_name', 'address', 'phone_number', 'dob', 'gender']
        widgets = {
            'user': forms.Select(attrs={'class': 'form-control'}),
            'full_name': forms.TextInput(attrs={'class': 'form-control'}),
            'address': forms.TextInput(attrs={'class': 'form-control'}),
            'phone_number': forms.NumberInput(attrs={'class': 'form-control'}),
            'dob': forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}),
            'gender': forms.Select(attrs={'class': 'form-control'}),
        }

    def __init__(self, user_id, *args, **kwargs):
        super(ProfileForms, self).__init__(*args, **kwargs)
        self.fields['gender'].empty_label = 'Select Gender'
        self.fields['user'].empty_label = None
        self.fields['user'].queryset = MyUser.objects.filter(email=user_id)


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profiles
        fields = ['user', 'profile_image', 'full_name', 'address', 'phone_number', 'dob', 'gender']
        widgets = {
            'user': forms.Select(attrs={'class': 'form-control'}),
            'full_name': forms.TextInput(attrs={'class': 'form-control'}),
            'address': forms.TextInput(attrs={'class': 'form-control'}),
            'phone_number': forms.NumberInput(attrs={'class': 'form-control'}),
            'dob': forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}),
            'gender': forms.Select(attrs={'class': 'form-control'}),
            'rf_id': forms.TextInput(attrs={'class': 'form-control'}),
        }

    def __init__(self, user_id, *args, **kwargs):
        super(ProfileUpdateForm, self).__init__(*args, **kwargs)
        self.fields['gender'].empty_label = 'Select Gender'
        self.fields['user'].empty_label = None
        self.fields['user'].queryset = MyUser.objects.filter(email=user_id)

profiles/views.py
from django.shortcuts import render

# Create your views here.

user_dash/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Sum, Case, When
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import ListView, CreateView, UpdateView

from books.models import Book, LendBook, BookCopies
from profiles.models import Profiles
from .forms import ProfileForms, ProfileUpdateForm
from .models import RequestBook
from datetime import date
from decorator import is_user


@method_decorator(is_user(), name='dispatch')
class BookListView(ListView):
    model = Book
    template_name = 'user_dash/books_list_view.html'
    context_object_name = 'books'


@method_decorator(is_user(), name='dispatch')
class MyBookLendHistory(ListView):
    model = LendBook
    template_name = 'user_dash/my_book_history.html'
    context_object_name = 'books'

    def get_queryset(self):
        books = LendBook.objects.filter(user=self.request.user)
        for book in books:
            if not book.is_return:
                diff_days = (((date.today() - book.date_of_issue)).days)
                if diff_days > 5:
                    book.fine = (diff_days - 5) * 5

        return books


@method_decorator(is_user(), name='dispatch')
class ViewRequestBook(ListView):
    model = RequestBook
    template_name = 'user_dash/my_book_request.html'
    context_object_name = 'books'

    def get_queryset(self):
        return RequestBook.objects.filter(user=self.request.user)


@is_user()
def request_book(request, pk):
    if request.method == 'GET':
        book_id = pk
        book = Book.objects.get(pk=book_id)
        book_copies = BookCopies.objects.filter(book__pk=book.pk).filter(is_book_available=True)
        if book_copies:
            req_count = RequestBook.objects.filter(user=request.user).filter(req_date=date.today()).count()
            if req_count < 3:
                try:
                    RequestBook.objects.create(
                        user=request.user,
                        books=book,
                    )
                except:
                    messages.error(request, 'cannot request same book twice')
                    return redirect('user_dash:request_book_list_view')
                messages.success(request, 'book requested successfully')
                return redirect('user_dash:request_book_list_view')
            else:
                messages.error(request, 'cannot request book more than 3 in one day')
                return redirect('user_dash:request_book_list_view')

        else:
            messages.error(request, 'cannot request book more than 3 in one day')
            return redirect('user_dash:book_list')


@method_decorator(login_required(), name='dispatch')
class CreateProfile(CreateView):
    form_class = ProfileForms
    template_name = 'user_dash/profile_create_update.html'

    def get_success_url(self):
        return reverse_lazy('user_dash:profile_list_view')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user_id'] = self.request.user
        return kwargs

    def get(self, *args, **kwargs):
        if Profiles.objects.filter(user__email=self.request.user).exists():
            return redirect('user_dash:profile_list_view')
        return super(CreateProfile, self).get(*args, **kwargs)

# listing user profile
@method_decorator(login_required(), name='dispatch')
class ProfileListView(ListView):
    model = Profiles
    template_name = 'user_dash/profile_view.html'
    context_object_name = 'profiles'

    def get_queryset(self):
        queryset = Profiles.objects.filter(user__email=self.request.user)
        return queryset

    def get(self, *args, **kwargs):
        if not Profiles.objects.filter(user__email=self.request.user).exists():
            return redirect('user_dash:profile_create')
        return super(ProfileListView, self).get(*args, **kwargs)


@method_decorator(login_required(), name='dispatch')
class ProfileUpdateView(UpdateView):
    form_class = ProfileUpdateForm
    success_url = "/userdash/profile/view/"
    template_name = 'user_dash/update_profile.html'

    def get_object(self, **kwargs):
        return Profiles.objects.get(user=self.request.user)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user_id'] = self.request.user
        return kwargs

user_dash/templates/user_dash/books_list_view.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Book{% endblock %}
{% block body %}
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Books</h1>

    </div>
    <div class="row">

        <!-- DataTable with Hover -->
        <div class="col-lg-12">
            <div class="card mb-4">
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                </div>
                <div class="table-responsive p-3">
                    <table class="table table-bordered table-striped table-vcenter js-dataTable-full">
                        <thead class="thead-light">
                        <tr>
                            <th>SN</th>
                            <th>Author</th>
                            <th>Title</th>
                            <th>Categories</th>
                            <th>Publication</th>
                            <th>Published Date</th>
                            <th>Action</th>
                        </tr>
                        </thead>

                        <tbody>
                        {% for book in books %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ book.author }}</td>
                                <td>{{ book.title }}</td>
                                <td>{{ book.category.name }}</td>
                                <td>{{ book.publication_name }}</td>
                                <td>{{ book.publication_date }}</td>
                                <td><a href="{% url 'user_dash:request_book' book.pk %}"> Reserve a book</a></td>


                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

user_dash/templates/user_dash/my_book_history.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Book{% endblock %}
{% block body %}
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">My Books History</h1>

    </div>
    <div class="row">

        <!-- DataTable with Hover -->
        <div class="col-lg-12">
            <div class="card mb-4">
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                </div>
                <div class="table-responsive p-3">
                    <table class="table table-bordered table-striped table-vcenter js-dataTable-full">
                        <thead class="thead-light">
                        <tr>
                            <th>SN</th>
                            <th>Book</th>
                            <th>Author</th>
                            <th>Fine</th>
                            <th>Date Of Issue</th>
                            <th>Date Of return</th>
                            <th>Is return</th>

                        </tr>
                        </thead>

                        <tbody>
                        {% for book in books %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ book.book.book.title }}</td>
                                <td>{{ book.book.book.author }}</td>
                                <td>{{ book.fine }}</td>
                                <td>{{ book.date_of_issue }}</td>
                                <td>{{ book.date_of_return }}</td>
                                <td>{{ book.is_return }}</td>

                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

user_dash/templates/user_dash/my_book_request.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Book{% endblock %}
{% block body %}
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">My Books History</h1>

    </div>
    {% if messages %}
                    {% for message in messages %}
                        <div{% if message.tags == 'error' %} class="alert alert-danger" {% else %} class="alert alert-success" {% endif %}>{{ message }}</div>
                    {% endfor %}
            {% endif %}
    <div class="row">

        <!-- DataTable with Hover -->
        <div class="col-lg-12">
            <div class="card mb-4">
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                </div>
                <div class="table-responsive p-3">
                    <table class="table table-bordered table-striped table-vcenter js-dataTable-full">
                        <thead class="thead-light">
                        <tr>
                            <th>SN</th>
                            <th>User</th>
                            <th>Title</th>
                            <th>Requested Date</th>
                            <th>Is Request Cancelled</th>

                        </tr>
                        </thead>

                        <tbody>
                        {% for book in books %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ book.user }}</td>
                                <td>{{ book.books.title }}</td>
                                <td>{{ book.req_date }}</td>
                                <td>{{ book.is_req_cancelled }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

user_dash/templates/user_dash/profile_create_update.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Profile{% endblock %}
#04A3ED
{% block style %}
    <style>
        .drop-zone {
            max-width: 300px;
            height: 300px;
            padding: 15px;
            display: flex;
            align-items: center;
            justify-content: center;
            text-align: center;
            font-family: "Quicksand", sans-serif;
            font-weight: 500;
            font-size: 20px;
            cursor: pointer;
            color: #cccccc;
            border: 4px solid #04A3ED;
            border-radius: 10px;
        }

        .drop-zone--over {
            border-style: solid;
        }

        .drop-zone__input {
            display: none;
        }

        .drop-zone__thumb {
            width: 100%;
            height: 100%;
            border-radius: 10px;
            overflow: hidden;
            background-color: #cccccc;
            background-size: cover;
            position: relative;
        }

        .drop-zone__thumb::after {
            content: attr(data-label);
            position: absolute;
            bottom: 0;
            left: 0;
            width: 100%;
            padding: 5px 0;
            color: #ffffff;
            background: rgba(0, 0, 0, 0.75);
            font-size: 14px;
            text-align: center;
        }
    </style>
{% endblock %}
{% block body %}

    <div class="d-sm-flex  mb-4">
        <h1 class="h3 mb-0 text-gray-800">Create Profile</h1>
    </div>

    <div class="row mb-3 ">
        <!-- Earnings (Monthly) Card Example -->
        <div class="col-xl-5 col-md-6 mb-4">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
{#                <div class="drop-zone">#}
{#                    <span class="drop-zone__prompt">Drop Student Profile Picture here or click to upload</span>#}
                    <input type="file" name="profile_image" accept="image/*" class="drop-zone__input">
{#                </div>#}
                {{ form.errors.profile_image }}
                <div class="mt-3">
                    <div class="form-group">
                        <label for="user">User</label>
                        {{ form.user }}<br>
                        {{ form.errors.user }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="full_name">Full Name</label>
                    {{ form.full_name }}<br>
                    {{ form.errors.full_name }}
                </div>
                <div class="form-group">
                    <label for="address">Address</label>
                    {{ form.address }}<br>
                    {{ form.errors.address }}
                </div>
                <div class="form-group">
                    <label for="phone_number">Phone Number</label>
                    {{ form.phone_number }}<br>
                    {{ form.errors.phone_number }}
                </div>
                <div class="form-group">
                    <label for="dob">Date Of Birth</label>
                    {{ form.dob }}<br>
                    {{ form.errors.dob }}
                </div>

                <div class="form-group">
                    <label for="gender">Gender</label>
                    {{ form.gender }}<br>
                    {{ form.errors.gender }}
                </div>


                <input type="submit" value="Submit" class="btn btn-info">
        </div>

        </form>

    </div>


    </div>
{% endblock %}
{% block js %}
    <script>
        document.querySelectorAll(".drop-zone__input").forEach((inputElement) => {
            const dropZoneElement = inputElement.closest(".drop-zone");

            dropZoneElement.addEventListener("click", (e) => {
                inputElement.click();
            });

            inputElement.addEventListener("change", (e) => {
                if (inputElement.files.length) {
                    updateThumbnail(dropZoneElement, inputElement.files[0]);
                }
            });

            dropZoneElement.addEventListener("dragover", (e) => {
                e.preventDefault();
                dropZoneElement.classList.add("drop-zone--over");
            });

            ["dragleave", "dragend"].forEach((type) => {
                dropZoneElement.addEventListener(type, (e) => {
                    dropZoneElement.classList.remove("drop-zone--over");
                });
            });

            dropZoneElement.addEventListener("drop", (e) => {
                e.preventDefault();

                if (e.dataTransfer.files.length) {
                    inputElement.files = e.dataTransfer.files;
                    updateThumbnail(dropZoneElement, e.dataTransfer.files[0]);
                }

                dropZoneElement.classList.remove("drop-zone--over");
            });
        });

        /**
         * Updates the thumbnail on a drop zone element.
         *
         * @param {HTMLElement} dropZoneElement
         * @param {File} file
         */
        function updateThumbnail(dropZoneElement, file) {
            let thumbnailElement = dropZoneElement.querySelector(".drop-zone__thumb");

            // First time - remove the prompt
            if (dropZoneElement.querySelector(".drop-zone__prompt")) {
                dropZoneElement.querySelector(".drop-zone__prompt").remove();
            }

            // First time - there is no thumbnail element, so lets create it
            if (!thumbnailElement) {
                thumbnailElement = document.createElement("div");
                thumbnailElement.classList.add("drop-zone__thumb");
                dropZoneElement.appendChild(thumbnailElement);
            }

            thumbnailElement.dataset.label = file.name;

            // Show thumbnail for image files
            if (file.type.startsWith("image/")) {
                const reader = new FileReader();

                reader.readAsDataURL(file);
                reader.onload = () => {
                    thumbnailElement.style.backgroundImage = `url('${reader.result}')`;
                };
            } else {
                thumbnailElement.style.backgroundImage = null;
            }
        }

    </script>
{% endblock %}

user_dash/templates/user_dash/profile_view.html
{% extends 'base.html' %}
{% load static %}
{% block title %}View Profile{% endblock %}
{% block body %}
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">View profile</h1>
    </div>
    <div class="row">

        <!-- DataTable with Hover -->
        <div class="col-lg-12">
            <div class="card mb-4">
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                </div>
                <div class="table-responsive p-3">
                    {% for profile in profiles %}
                        Image:<br>
                        {% if profile.profile_image %}
                            <img src="{{ profile.profile_image.url }}" height="350" width="200"><br>
                        {% else %}
                            No Profile Image<br>
                        {% endif %}
                        Name: {{ profile.full_name }}<br>
                        Email: {{ profile.user.email }}<br>
                        Address : {{ profile.address }}<br>
                        Phone Number : {{ profile.phone_number }}<br>
                        Date of birth : {{ profile.dob }}<br>
                        RFID : {{ profile.rf_id }}<br><br>
                        <a href="{% url 'user_dash:profile_update' %}" class="btn btn-success">Update Profile</a><br>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

user_dash/templates/user_dash/update_profile.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Profile{% endblock %}
#04A3ED
{% block style %}
    <style>
        .drop-zone {
            max-width: 300px;
            height: 300px;
            padding: 15px;
            display: flex;
            align-items: center;
            justify-content: center;
            text-align: center;
            font-family: "Quicksand", sans-serif;
            font-weight: 500;
            font-size: 20px;
            cursor: pointer;
            color: #cccccc;
            border: 4px solid #04A3ED;
            border-radius: 10px;
        }

        .drop-zone--over {
            border-style: solid;
        }

        .drop-zone__input {
            display: none;
        }

        .drop-zone__thumb {
            width: 100%;
            height: 100%;
            border-radius: 10px;
            overflow: hidden;
            background-color: #cccccc;
            background-size: cover;
            position: relative;
        }

        .drop-zone__thumb::after {
            content: attr(data-label);
            position: absolute;
            bottom: 0;
            left: 0;
            width: 100%;
            padding: 5px 0;
            color: #ffffff;
            background: rgba(0, 0, 0, 0.75);
            font-size: 14px;
            text-align: center;
        }
    </style>
{% endblock %}
{% block body %}

    <div class="d-sm-flex  mb-4">
        <h1 class="h3 mb-0 text-gray-800">Create Profile</h1>
    </div>

    <div class="row mb-3 ">
        <!-- Earnings (Monthly) Card Example -->
        <div class="col-xl-5 col-md-6 mb-4">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <input type="file" name="profile_image" accept="image/*" class="drop-zone__input">

                {{ form.errors.profile_image }}
                <div class="mt-3">
                    <div class="form-group">
                        <label for="user">User</label>
                        {{ form.user }}<br>
                        {{ form.errors.user }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="full_name">Full Name</label>
                    {{ form.full_name }}<br>
                    {{ form.errors.full_name }}
                </div>
                <div class="form-group">
                    <label for="address">Address</label>
                    {{ form.address }}<br>
                    {{ form.errors.address }}
                </div>
                <div class="form-group">
                    <label for="phone_number">Phone Number</label>
                    {{ form.phone_number }}<br>
                    {{ form.errors.phone_number }}
                </div>
                <div class="form-group">
                    <label for="dob">Date Of Birth</label>
                    {{ form.dob }}<br>
                    {{ form.errors.dob }}
                </div>

                <div class="form-group">
                    <label for="gender">Gender</label>
                    {{ form.gender }}<br>
                    {{ form.errors.gender }}
                </div>


                <input type="submit" value="Submit" class="btn btn-info">
        </div>

        </form>

    </div>


    </div>
{% endblock %}
{% block js %}
    <script>
        document.querySelectorAll(".drop-zone__input").forEach((inputElement) => {
            const dropZoneElement = inputElement.closest(".drop-zone");

            dropZoneElement.addEventListener("click", (e) => {
                inputElement.click();
            });

            inputElement.addEventListener("change", (e) => {
                if (inputElement.files.length) {
                    updateThumbnail(dropZoneElement, inputElement.files[0]);
                }
            });

            dropZoneElement.addEventListener("dragover", (e) => {
                e.preventDefault();
                dropZoneElement.classList.add("drop-zone--over");
            });

            ["dragleave", "dragend"].forEach((type) => {
                dropZoneElement.addEventListener(type, (e) => {
                    dropZoneElement.classList.remove("drop-zone--over");
                });
            });

            dropZoneElement.addEventListener("drop", (e) => {
                e.preventDefault();

                if (e.dataTransfer.files.length) {
                    inputElement.files = e.dataTransfer.files;
                    updateThumbnail(dropZoneElement, e.dataTransfer.files[0]);
                }

                dropZoneElement.classList.remove("drop-zone--over");
            });
        });

        /**
         * Updates the thumbnail on a drop zone element.
         *
         * @param {HTMLElement} dropZoneElement
         * @param {File} file
         */
        function updateThumbnail(dropZoneElement, file) {
            let thumbnailElement = dropZoneElement.querySelector(".drop-zone__thumb");

            // First time - remove the prompt
            if (dropZoneElement.querySelector(".drop-zone__prompt")) {
                dropZoneElement.querySelector(".drop-zone__prompt").remove();
            }

            // First time - there is no thumbnail element, so lets create it
            if (!thumbnailElement) {
                thumbnailElement = document.createElement("div");
                thumbnailElement.classList.add("drop-zone__thumb");
                dropZoneElement.appendChild(thumbnailElement);
            }

            thumbnailElement.dataset.label = file.name;

            // Show thumbnail for image files
            if (file.type.startsWith("image/")) {
                const reader = new FileReader();

                reader.readAsDataURL(file);
                reader.onload = () => {
                    thumbnailElement.style.backgroundImage = `url('${reader.result}')`;
                };
            } else {
                thumbnailElement.style.backgroundImage = null;
            }
        }

    </script>
{% endblock %}