LibraryManagementSystem/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('accounts.urls')),
                  path('admindash/', include('admin_dash.urls')),
                  path('userdash/', include('user_dash.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path, include
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('change/password', views.password_change, name='password_change'),
    path('', views.login, name='login'),
    path('send/email/verification', views.send_email_verification_code, name='send_email_verification_code'),
    path('email/verify', views.verify_email, name='verify_email'),
    path('logout', views.logout, name='logout')
]

admin_dash/urls.py
from django.urls import path
from . import views

app_name = 'admin_dash'

urlpatterns = [
    path('', views.home, name='home'),
    # users
    path('add/users/', views.UsersCreateView.as_view(), name='add_users'),
    path('view/users/', views.UserListView.as_view(), name='user_list_view'),
    # profile
    path('update/user/<str:pk>', views.UserUpdateView.as_view(), name='update_user'),
    path('block/user/<str:email>', views.block_user, name='block_user'),
    path('verify/user/email/<str:email>', views.verify_email, name='verify_email'),
    path('verify/user/<str:email>', views.verify_user, name='verify_user'),
    path('profile/view/<str:pk>', views.ProfileListView.as_view(), name='profile_list_view'),
    path('profile/create/<str:pk>', views.CreateProfile.as_view(), name='create_profile'),
    path('profile/update/<str:pk>', views.ProfileUpdateView.as_view(), name='profile_update'),
    # books
    path('book/create/', views.BookCreateView.as_view(), name='book_create'),
    path('book/update/<str:pk>', views.BookUpdate.as_view(), name='book_update'),
    path('book/list/', views.BookListView.as_view(), name='book_list'),
    path('book/copies/create/<str:pk>', views.BookCopiesCreateView.as_view(), name='book_copies_create'),
    path('book/copies/view/<str:pk>', views.BookCopiesListView.as_view(), name='book_copies_list'),
    # lend book
    path('book/lend/student/', views.user_id, name='student'),
    path('book/student/book/', views.book, name='book'),
    path('book/lend/student/book/', views.user_book, name='user_book'),
    path('book/lend/student/book/conform', views.lend_book, name='lend_book'),
    path('book/return/', views.return_book, name='return_book'),
    path('book/return/conform/', views.return_conform, name='return_book_conform'),
    # request book
    path('book/request/view', views.RequestBookListView.as_view(), name='request_book_view'),
    path('book/request/cancel/<str:pk>', views.cancel_book_request, name='cancel_book_request'),
    #book history
    path('book/history/',views.MyBookLendHistory.as_view(),name='book_history')
]

user_dash/urls.py
from django.urls import path
from . import views

app_name = 'user_dash'

urlpatterns = [
    path('book/list/', views.BookListView.as_view(), name='book_list'),
    path('book/history/', views.MyBookLendHistory.as_view(), name='book_list_history'),
    path('book/request/view', views.ViewRequestBook.as_view(), name='request_book_list_view'),
    path('book/request/<str:pk>', views.request_book, name='request_book'),
    path('profile/create/', views.CreateProfile.as_view(), name='profile_create'),
    path('profile/view/', views.ProfileListView.as_view(), name='profile_list_view'),
    path('profile/update/', views.ProfileUpdateView.as_view(), name='profile_update'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Meta -->
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"/>

    <!-- Document title -->
    <title>{% block title %}{% endblock %}</title>

    <meta name="description" content="LMS - Library Management System"/>
    <meta name="author" content="LMS"/>
    <meta name="robots" content="noindex, nofollow"/>

    <!-- Google fonts -->
    <link rel="stylesheet"
          href="http://fonts.googleapis.com/css?family=Roboto:300,400,400italic,500,900%7CRoboto+Slab:300,400%7CRoboto+Mono:400"/>

    <!-- Page JS Plugins CSS -->
    <link rel="stylesheet" href="{% static 'dashboard/assets/js/datatables/jquery.dataTables.min.css' %}"/>

    <!-- CSS stylesheets -->
    <link rel="stylesheet" id="css-font-awesome" href="{% static 'dashboard/assets/css/font-awesome.css' %}"/>
    <link rel="stylesheet" id="css-ionicons" href="{% static 'dashboard/assets/css/ionicons.css' %}"/>
    <link rel="stylesheet" id="css-bootstrap" href="{% static 'dashboard/assets/css/bootstrap.css' %}"/>
    <link rel="stylesheet" id="css-app" href="{% static 'dashboard/assets/css/app.css' %}"/>
    <!-- End Stylesheets -->
    {% block linkcss %}{% endblock %}
    {% block style %}{% endblock %}
</head>

<body id="page-top">
<body class="app-ui layout-has-drawer layout-has-fixed-header">
<div class="app-layout-canvas">
    <div class="app-layout-container">

        <!-- Drawer -->
        <aside class="app-layout-drawer">

            <!-- Drawer scroll area -->
            <div class="app-layout-drawer-scroll">
                <!-- Drawer logo -->
                <div id="logo" class="drawer-header">
                    <a href="/">
                        <h5 class="text-center" style="color: black;">Library Management System</h5>
                    </a>
                </div>

                <!-- Drawer navigation -->
                <nav class="drawer-main">
                    <ul class="nav nav-drawer">


                        {% if request.user.is_admin %}
                            <li class="nav-item nav-drawer-header">Home</li>

                            <li class="nav-item active">
                                <a class="nav-link" href="{% url 'admin_dash:home' %}">
                                    <i class="ion-speedometer fa-4x"></i>
                                    <span>Dashboard</span></a>
                            </li>

                            <li class="nav-item nav-drawer-header">Menu</li>

                            <hr class="sidebar-divider">

                            <li class="nav-item active">
                                <a class="nav-link" href="{% url 'admin_dash:user_list_view' %}">
                                    <i class="ion-person fa-4x"></i>
                                    <span>Users</span></a>
                            </li>

                            <li class="nav-item active">
                                <a class="nav-link" href="{% url 'admin_dash:book_list' %}">
                                    <i class="ion-ios-book"></i>
                                    <span>Book List</span></a>
                            </li>

                            <li class="nav-item active">
                                <a class="nav-link" href="{% url 'admin_dash:student' %}">
                                    <i class="ion-ios-book-outline"></i>
                                    <span>Book Lend</span></a>
                            </li>

                            <li class="nav-item active">
                                <a class="nav-link" href="{% url 'admin_dash:book_history' %}">
                                    <i class="ion-ios-copy"></i>
                                    <span>Book Lend History</span></a>
                            </li>

                            <li class="nav-item active">
                                <a class="nav-link" href="{% url 'admin_dash:request_book_view' %}">
                                    <i class="ion-pull-request"></i>
                                    <span>Book Request</span></a>
                            </li>

                            <li class="nav-item active">
                                <a class="nav-link" href="{% url 'admin_dash:return_book' %}">
                                    <i class="ion-android-hand"></i>
                                    <span>Book Return</span></a>
                            </li>





                            <li class="nav-item active">
                                <a class="nav-link" href="{% url 'accounts:logout' %}">
                                    <i class="ion-locked"></i>
                                    <span>Logout</span></a>
                            </li>
                        {% else %}

                            <li class="nav-item active">
                                <a class="nav-link" href="{% url 'user_dash:profile_list_view' %}">
                                    <i class="ion-person"></i>
                                    <span>Profile</span></a>
                            </li>

                            <li class="nav-item active">
                                <a class="nav-link" href="{% url 'user_dash:book_list' %}">
                                    <i class="ion-ios-book-outline"></i>
                                    <span>Book</span></a>
                            </li>
                            <li class="nav-item active">
                                <a class="nav-link" href="{% url 'user_dash:book_list_history' %}">
                                    <i class="ion-pull-request"></i>
                                    <span>My Book Lend History</span></a>
                            </li>

                            <li class="nav-item active">
                                <a class="nav-link" href="{% url 'user_dash:request_book_list_view' %}">
                                    <i class="ion-ios-pulse"></i>
                                    <span>My Request History</span></a>
                            </li>

                            <li class="nav-item active">
                                <a class="nav-link" href="{% url 'accounts:password_change' %}">
                                    <i class="ion-lock-combination"></i>
                                    <span>Change Password</span></a>
                            </li>

                            <li class="nav-item active">
                                <a class="nav-link" href="{% url 'accounts:logout' %}">
                                    <i class="ion-locked"></i>
                                    <span>Logout</span></a>
                            </li>

                        {% endif %}
                    </ul>
                </nav>
                <!-- End drawer navigation -->

            </div>
            <!-- End drawer scroll area -->
        </aside>
        <!-- End drawer -->

        <!-- Header -->
        <header class="app-layout-header">
            <nav class="navbar navbar-default">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                                data-target="#header-navbar-collapse" aria-expanded="false">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <button class="pull-left hidden-lg hidden-md navbar-toggle" type="button"
                                data-toggle="layout" data-action="sidebar_toggle">
                            <span class="sr-only">Toggle drawer</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>

                    </div>

                    <div class="collapse navbar-collapse" id="header-navbar-collapse">

                        <!-- .navbar-left -->

                        <ul class="nav navbar-nav navbar-right navbar-toolbar">

                            <li class="dropdown dropdown-profile">
                                <a href="javascript:void(0)" data-toggle="dropdown">
                                    <span class="">{{ request.user }}<span class="caret"></span></span>

                                </a>
                                <ul class="dropdown-menu dropdown-menu-right">

                                    <li>
                                        <a href="{% url 'accounts:logout' %}">Logout</a>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                        <!-- .navbar-right -->
                    </div>
                </div>
                <!-- .container-fluid -->
            </nav>
            <!-- .navbar-default -->
        </header>
        <!-- End header -->

        <main class="app-layout-content">

            <!-- Page Content -->
            <div class="container-fluid">
                <!-- Dynamic Table Full -->
                <div class="card">
{#                    <div class="card-header">#}
                        <!-- <h4>Heading</h4> -->
{#                    </div>#}
                    <div class="card-block">
                        {% block body %}

                        {% endblock %}

                    </div>
                    <!-- .card-block -->
                </div>
                <!-- .card -->
                <!-- End Dynamic Table Full -->

            </div>
            <!-- .container-fluid -->
            <!-- End Page Content -->

        </main>

    </div>
    <!-- .app-layout-container -->
</div>
<!-- .app-layout-canvas -->

<!-- Apps Modal -->
<!-- Opens from the button in the header -->
<div id="apps-modal" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-sm modal-dialog modal-dialog-top">
        <div class="modal-content">
            <!-- Apps card -->
            <div class="card m-b-0">
                <div class="card-header bg-app bg-inverse">
                    <h4>Apps</h4>
                    <ul class="card-actions">
                        <li>
                            <button data-dismiss="modal" type="button"><i class="ion-close"></i></button>
                        </li>
                    </ul>
                </div>
                <div class="card-block">
                    <div class="row text-center">
                        <div class="col-xs-6">
                            <a class="card card-block m-b-0 bg-app-secondary bg-inverse" href="/">
                                <i class="ion-speedometer fa-4x"></i>
                                <p>Admin</p>
                            </a>
                        </div>
                        <div class="col-xs-6">
                            <a class="card card-block m-b-0 bg-app-tertiary bg-inverse" href="/">
                                <i class="ion-laptop fa-4x"></i>
                                <p>Frontend</p>
                            </a>
                        </div>
                    </div>
                </div>
                <!-- .card-block -->
            </div>
            <!-- End Apps card -->
        </div>
    </div>
</div>
<!-- End Apps Modal -->

<div class="app-ui-mask-modal"></div>


<!-- Core JS: jQuery, Bootstrap, slimScroll, scrollLock and App.js -->
<script src="{% static 'dashboard/assets/js/jquery.min.js' %}"></script>
<script src="{% static 'dashboard/assets/js/bootstrap.min.js' %}"></script>
<script src="{% static 'dashboard/assets/js/jquery.slimscroll.min.js' %}"></script>
<script src="{% static 'dashboard/assets/js/jquery.scrollLock.min.js' %}"></script>
<script src="{% static 'dashboard/assets/js/jquery.placeholder.min.js' %}"></script>
<script src="{% static 'dashboard/assets/js/app.js' %}"></script>

<!-- Page JS Plugins -->
<script src="{% static 'dashboard/assets/js/datatables/jquery.dataTables.min.js' %}"></script>

<!-- Page JS Code -->
<script src="{% static 'dashboard/assets/js/datatables/base_tables_datatables.js' %}"></script>
{% block js %}
{% endblock %}
</body>

</html>